language: node_js
node_js:
  - 0.8
  - 0.10
before_install:
  - sudo add-apt-repository -y ppa:jon-severinsson/ffmpeg
  - sudo apt-get update -qq
  - sudo apt-get install -qq ffmpeg libavcodec-extra-53